language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: TODO
branches:
  only:
  - dev
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
php:
- 7.0.8
- 7.1
- nightly
env:
- WP_VERSION=latest WP_MULTISITE=1 TRAVIS_NODE_VERSION="6"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - node_modules
  - vendor
before_install:
- source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
install:
- node -v
- npm install -g yarn
- yarn
- composer install
before_script:
- if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]] && php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- git clone --depth=1 https://github.com/pressbooks/pressbooks.git ../pressbooks
- cd ../pressbooks && composer install --no-dev
- cd ../pressbooks-lti-provider
script:
- yarn run test
- yarn run build:production
- vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/ bin/
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
- composer install --no-dev --optimize-autoloader
- cd ../
- zip -9 -ry $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip $TRAVIS_PROJECT_SLUG
  -x *.git* *assets/\* *bin/\* *node_modules/\* *tests/\* *.editorconfig* *.gitattributes*
  *.github* *.gitignore* *.phpstorm.meta.php* *.travis.yml* *.tx/\* *Gruntfile.js*
  *package-lock.json* *phpcs.ruleset.xml* *phpunit.xml* *webpack.mix.js* *yarn.lock*
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JTRg6+ELSJ78tGhd/V3HvpdkiTtfRcUWFA5Mi6f8EucEFwcSNX2fy4kIIDqDefvVdJxZV5HvPnzj6D13cfc34hIz/MEjOJsa+9/Xw0LKHDDFnlia9PctXUM8gOtFwAnr1LzkXfG2L1TL/w1Bxq5KyWMJ2m8vtIfaLzqcaLV0Wv38csCQk2dJxPnq7SQ92+8aTzaW9lIiSoDNxtuzzFkdOOGzxHAsOKbJHN/5LEdNqnygJb9xGZ10VK/PCl3pd+oCFabzs7uHhxF7jfrFQAkHr/Ajya53X68DHOF00fD0FSzDcmejD0jmj3p4HceLthQVYbScj+wN0OVoGFZluLEbcP/MkRiwzoaHzV9ywtE5CQl0spRaObimiCssxAi8LZ0Nhp3mB5Q1Lo6uVaxfHxwprpgKDZADLphNvMbTB/EvN34Y4+JEQ9ffTzVsGPDhg2dDjymMDCvT8B0jivBz6mitbw2RUjOuykb9RMz6S6YGcbVRDWmUONHR/n6axwLhVD+gd3B/iY6GUvPcCo0wXYG5RqN06htiaJVWencin0MQbnZgfbhQdaGh+P+tXqTDdkuGquv+gvYxuLPqEQiDt/VoL3C4Hh+7pcAz0bStg6CNwbXFUJnXwJnWuX52FJIM474nI7V4S/AZbqDwW+L+kVIqk7UnWEnuNE5tBWWzUTd+4wk=
  file: "pressbooks-lti-provider-$TRAVIS_TAG.zip"
  on:
    tags: true
    repo: pressbooks/pressbooks-lti-provider
