name: Update translations from Transifex

on:
  push:
    branches:
    - dev

jobs:
  generate-mo:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[tx-pull]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install Transifex Client
      run: sudo pip install transifex-client
    - name: Configure Transifex Client
      run: tx pull -a
      env:
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
    - name: Install xgettext
      run: sudo apt-get install -y gettext
    - name: Generate MO files
      run: for file in languages/*.po ; do msgfmt $file -o `echo $file | sed 's/\(.*\.\)po/\1mo/'` ; done
    - name: Create pull request with updated content
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'chore: update translations'
        title: 'chore: update translations'
        body: 'Update translations from [Transifex](https://www.transifex.com/pressbooks/pressbooks-lti-provider/).'
        branch: update-translations
        base: dev
